### PR TITLE
Use webpack as build tool + remove unnecessary functionality

### PR DESCRIPTION
**Pull request by s0ber**
@paraboom Hello, man! Hope you're doing great.
Can you please take a look at this PR?

### CODE REVIEW

**Comment by paraboom** [comment]
Hey, man! I'm great!

**Comment by paraboom** [comment]
Totally forgot, this lib is in my account :) If you want we can move it to another account.

**Comment by s0ber** [comment]
For me it's fine to keep it here. Also, now it is really light and useful in modern architectures!

**Comment by s0ber** [comment]
Can you please merge and publish this, when it will be ready?
In two words, I removed `store.js` and `echo.js` dependencies from here, also I removed `undercore.js` dependency. So this is lib is really light now and can be plugged in any project.

**Pull request merged**
